name: alias
description: A new Flutter package project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  flutter_bloc: ^9.1.0
  flutter_animate: ^4.5.2
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  cloud_firestore: ^5.6.6
  firebase_core: ^3.13.0

  app_core:
    path: ../../core/app_core

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true