name: boardify
description: "Boardify â€“ Your Pocket Board Game Hub!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.2"

dependencies:
  cloud_firestore: ^5.6.6
  equatable: ^2.0.7
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  go_router: ^14.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: any
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/flags/