name: boardify
description: "Boardify â€“ Your Pocket Board Game Hub!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter: ">=3.35.7"

dependencies:
  cloud_firestore: ^6.1.0
  equatable: ^2.0.7
  firebase_core: ^4.2.1
  firebase_remote_config: ^6.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.1
  get_it: ^8.2.0
  go_router: ^16.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: any
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/flags/